/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projekt.spel;

public class App {
    public static final int rows=3;
    public static final int cols=3;


    public static void main(String[] args) {


    }
}
